import styles from "../../../styles/Mint/desoFlow.module.scss";

const DesoFlow = () => { 
    
    return (
        <!-- desoBlockchain steps -->
<app-step-one
  *ngIf="step === 2"
  (previous)="previousStep()"
  (next)="nextStep()"
  [mobile]="mobile"
  [animationType]="animationType"
  [oneEdition]="oneEdition"
  [multipleEditions]="multipleEditions"
  [isBuyNow]="isBuyNow"
  [openAuction]="openAuction"
  (selectOneEdition)="oneEditionSelected()"
  (selectMultipleEditions)="multipleEditionsSelected()"
  (selectBuyNow)="buyNowSelected()"
  (selectOpenAuction)="openAuctionSelected()"
></app-step-one>
<app-step-two
  *ngIf="step === 3"
  (previous)="previousStep()"
  (next)="nextStep()"
  (updateFilesInputCoverImage)="_handleFilesInputCoverImage($event)"
  (uploadContent)="_handleFilesInput($event)"
  (selectCategory)="selectCategory($event)"
  (selectionEditionNumber)="setEditionAmount($event)"
  (selectDescription)="setDescription($event)"
  (selectName)="setName($event)"
  (singleFileInput)="_handleFileInput($event)"
  [modelType]="modelType"
  [audioType]="audioType"
  [videoType]="videoType"
  [imageType]="imageType"
  [mobile]="mobile"
  [animationType]="animationType"
  [isUploading]="isUploading"
  [readyToStream]="readyToStream"
  [isBuyNow]="isBuyNow"
  [NAME_OF_PIECE]="NAME_OF_PIECE"
  [EDITIONAMOUNTNUM]="EDITIONAMOUNTNUM"
  [DESCRIPTION]="DESCRIPTION"
  [CATEGORY]="CATEGORY"
  [postImageArweaveSrc]="postImageArweaveSrc"
  [postVideoArweaveSrc]="postVideoArweaveSrc"
  [postAudioArweaveSrc]="postAudioArweaveSrc"
  [postModelArweaveSrc]="postModelArweaveSrc"
  [postVideoDESOSrc]="postVideoDESOSrc"
  [KEY]="KEY"
  [VALUE]="VALUE"
  (KVAdd)="addKV($event)"
  [KVMap]="KVMap"
  (KVDelete)="deleteKV($event)"
  [oneEdition]="oneEdition"
  [multipleEditions]="multipleEditions"
></app-step-two>
<app-step-three
  *ngIf="step === 4"
  (previous)="previousStep()"
  (next)="nextStep()"
  [mobile]="mobile"
  [animationType]="animationType"
  [isBuyNow]="isBuyNow"
  [openAuction]="openAuction"
  [postImageArweaveSrc]="postImageArweaveSrc"
  [postVideoArweaveSrc]="postVideoArweaveSrc"
  [postAudioArweaveSrc]="postAudioArweaveSrc"
  [postModelArweaveSrc]="postModelArweaveSrc"
  [postVideoDESOSrc]="postVideoDESOSrc"
  [additionalDESORoyalties]="additionalDESORoyalties"
  [additionalCoinRoyalties]="additionalCoinRoyalties"
  (setNewCoinRoyalty)="addNewCoinRoyalty($event)"
  (setNewDESORoyalty)="addNewDESORoyalty($event)"
  (removeRoyalty)="removeRoyalty($event)"
  (toggleUnlockable)="toggleUnlockableContent()"
  (toggleForSale)="togglePutForSale()"
  [CREATOR_ROYALTY]="CREATOR_ROYALTY"
  [COIN_ROYALTY]="COIN_ROYALTY"
  [MIN_PRICE]="MIN_PRICE"
  [PUT_FOR_SALE]="PUT_FOR_SALE"
  [UNLOCKABLE_CONTENT]="UNLOCKABLE_CONTENT"
  [BUY_NOW_PRICE_USD]="BUY_NOW_PRICE_USD"
  [PRICE_USD]="PRICE_USD"
  [buyNowPriceDESO]="buyNowPriceDESO"
  [isSubmitPress]="isSubmitPress"
  (setBidAmountUSD)="updateBidAmountUSD($event)"
  (setCoinRoyalty)="updateCoinRoyalty($event)"
  (setCreatorRoyalty)="updateCreatorRoyalty($event)"
  (setBuyNowBidAmountUSD)="updateBuyNowBidAmountUSD($event)"
  (setMinBidClicked)="handleMinBidClicked()"
  [minBidClicked]="minBidClicked"
  (mint)="_createPost()"
></app-step-three>
<app-step-four
  *ngIf="step === 5"
  (previous)="previousStep()"
  (next)="nextStep()"
  [mobile]="mobile"
  [animationType]="animationType"
  (openRepostModal)="openModal($event)"
  (seePost)="seePost()"
></app-step-four>
<app-right-side-one
  [postImageArweaveSrc]="postImageArweaveSrc"
  [isCoverImageUploading]="isCoverImageUploading"
  [modelType]="modelType"
  [audioType]="audioType"
  [readyToStream]="readyToStream"
  [postVideoDESOSrc]="postVideoDESOSrc"
  [videoUploadPercentage]="videoUploadPercentage"
  (updateFilesInputCoverImage)="_handleFilesInputCoverImage($event)"
  [step]="step"
  (deleteImage)="deleteImage()"
  *ngIf="!mobile && 1 < step && step < 4"
></app-right-side-one>
<app-right-side-two
  [audioType]="audioType"
  [videoType]="videoType"
  [MIN_PRICE]="MIN_PRICE"
  [NAME_OF_PIECE]="NAME_OF_PIECE"
  [postImageArweaveSrc]="postImageArweaveSrc"
  [postVideoArweaveSrc]="postVideoArweaveSrc"
  *ngIf="!mobile && step >= 4"
></app-right-side-two>

    )
}
export default DesoFlow;