import Head from "../node_modules/next/head";
import styles from "../styles/Home.module.scss";
import Header from "../components/header";
import LeftNav from "../components/leftNav";
export default function Home() {

  function login() {
    console.log(process.env.NEXT_PUBLIC_id);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header></Header>
        <LeftNav></LeftNav>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
