import Head from "../node_modules/next/head";
import styles from "../styles/Home.module.scss";
import Header from "../components/Navigation/header";
import LeftNav from "../components/Navigation/leftNav";
import {
  launchLoginFlow,
} from "../utils/global-context";
import { useEffect, useState } from "react";
import { useAppDispatch, useAppSelector } from "../utils/Redux/hooks";
import { setLocalNode } from "../utils/Redux/Slices/nodeSlice";
export default function Home() {
  // Redux
  const dispatch = useAppDispatch();
  let localNode = useAppSelector((state) => state.node.localNode);

  // State end

  // Functions
  function login() {
    launchLoginFlow();
  }
  // Functions end

  // Lifecycle methods
  useEffect(() => {
    
  }, []);
  // Lifycycle methods end

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* USE HERE sanitizedIdentityServiceURL */}
        <Header></Header>
        <button onClick={() => login()}>CLICK</button>
        <p>{localNode}</p>

        <LeftNav></LeftNav>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
